# Generated by Django 5.2.13 on 2026-04-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0005_live_analysis_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanalysisevent',
            name='match_period',
            field=models.CharField(choices=[('first_half', 'First half'), ('second_half', 'Second half')], default='first_half', max_length=20),
        ),
        migrations.AddField(
            model_name='liveanalysisevent',
            name='minute',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LiveAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField()),
                ('kickoff_time', models.TimeField()),
                ('venue', models.CharField(max_length=160)),
                ('home_away', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('weather', models.CharField(max_length=120)),
                ('played_position', models.CharField(max_length=60)),
                ('starter_status', models.CharField(choices=[('starter', 'Starter'), ('substitute', 'Substitute')], max_length=20)),
                ('minute_entered', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_notes', models.TextField(blank=True)),
                ('match_story', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=5)),
                ('intensity', models.PositiveSmallIntegerField(default=5)),
                ('focus', models.PositiveSmallIntegerField(default=5)),
                ('decision_making', models.PositiveSmallIntegerField(default=5)),
                ('resilience', models.PositiveSmallIntegerField(default=5)),
                ('anxiety', models.PositiveSmallIntegerField(default=5)),
                ('motivation', models.PositiveSmallIntegerField(default=5)),
                ('communication', models.PositiveSmallIntegerField(default=5)),
                ('discipline', models.PositiveSmallIntegerField(default=5)),
                ('emotional_control', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='live_analysis_sessions', to='valuation.player')),
            ],
            options={
                'db_table': 'live_analysis_sessions',
                'ordering': ['-observed_on', '-kickoff_time', '-id'],
            },
        ),
        migrations.AddField(
            model_name='liveanalysisevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='valuation.liveanalysissession'),
        ),
    ]
