# Generated by Django 5.2.13 on 2026-04-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0008_liveplayerevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerIntelligenceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=160)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('position_primary', models.CharField(blank=True, max_length=60)),
                ('secondary_positions', models.JSONField(blank=True, default=list)),
                ('dominant_foot', models.CharField(blank=True, choices=[('right', 'Direito'), ('left', 'Esquerdo'), ('both', 'Ambos')], max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_club', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, choices=[('professional', 'Profissional'), ('academy', 'Base')], max_length=20)),
                ('contract_months_remaining', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('squad_status', models.CharField(blank=True, choices=[('starter', 'Titular'), ('backup', 'Reserva'), ('rotation', 'Rotacao'), ('limited', 'Pouco utilizado'), ('recovering', 'Retorno de lesao')], max_length=20)),
                ('athlete_objectives', models.JSONField(blank=True, default=list)),
                ('analyst_notes', models.TextField(blank=True)),
                ('current_step', models.CharField(choices=[('athlete', 'Atleta'), ('club', 'Clube'), ('coach', 'Treinador'), ('game_model', 'Modelo de jogo'), ('competition', 'Concorrencia'), ('diagnosis', 'Diagnostico'), ('prognosis', 'Prognostico'), ('development', 'Plano'), ('report', 'Relatorio')], default='athlete', max_length=20)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_cases', to='valuation.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_cases', to='valuation.user')),
            ],
            options={
                'db_table': 'career_intelligence_cases',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CareerPrognosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('high_chance', 'Alta chance de se tornar titular'), ('moderate', 'Chance moderada com desenvolvimento'), ('context', 'Dependente do contexto'), ('hierarchy', 'Bloqueado por hierarquia'), ('unlikely_short', 'Curto prazo improvavel'), ('change', 'Necessidade de mudanca de ambiente')], max_length=20)),
                ('timeframe', models.CharField(choices=[('short', 'Curto prazo'), ('medium', 'Medio prazo'), ('long', 'Longo prazo')], max_length=10)),
                ('justification', models.TextField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prognosis', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'career_prognoses',
            },
        ),
        migrations.CreateModel(
            name='ClubCompetitiveContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=160)),
                ('competition', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('team_moment', models.CharField(choices=[('title_race', 'Disputa por titulo'), ('relegation', 'Luta contra rebaixamento'), ('rebuild', 'Reconstrucao'), ('development', 'Desenvolvimento')], max_length=20)),
                ('pressure_level', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baixa')], max_length=10)),
                ('club_philosophy', models.CharField(choices=[('development', 'Formador'), ('competitive', 'Competitivo'), ('mixed', 'Misto')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_context', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'club_competitive_contexts',
                'ordering': ['club_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=160)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('months_in_charge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile_type', models.CharField(choices=[('developer', 'Formador'), ('conservative', 'Conservador'), ('offensive', 'Ofensivo'), ('reactive', 'Reativo'), ('manager', 'Gestor')], max_length=20)),
                ('experience_preference', models.CharField(choices=[('experience', 'Experiencia'), ('youth', 'Juventude'), ('balanced', 'Equilibrado')], max_length=20)),
                ('academy_usage_history', models.TextField(blank=True)),
                ('physical_demand', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=10)),
                ('tactical_demand', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=10)),
                ('selection_criteria', models.JSONField(blank=True, default=list)),
                ('analyst_notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'coach_profiles',
                'ordering': ['coach_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_reason', models.CharField(choices=[('technical_gap', 'Inferioridade tecnica'), ('tactical_gap', 'Inferioridade tatica'), ('physical_gap', 'Inferioridade fisica'), ('intensity_gap', 'Falta de intensidade'), ('low_maturity', 'Baixa maturidade'), ('coach_prefers_experience', 'Preferencia do treinador por experientes'), ('hierarchy', 'Hierarquia consolidada'), ('game_model_fit', 'Incompatibilidade com o modelo'), ('injury_return', 'Retorno de lesao'), ('emotional', 'Questoes emocionais'), ('few_opportunities', 'Poucas oportunidades'), ('adaptation', 'Adaptacao ao clube'), ('other', 'Outros')], max_length=40)),
                ('secondary_reasons', models.JSONField(blank=True, default=list)),
                ('contextual_reasons', models.JSONField(blank=True, default=list)),
                ('other_reason', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'competitive_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='IndividualDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths_to_keep', models.TextField(blank=True)),
                ('short_term_priorities', models.TextField(blank=True)),
                ('medium_term_development', models.TextField(blank=True)),
                ('contextual_factors', models.TextField(blank=True)),
                ('mental_strategy', models.TextField(blank=True)),
                ('practical_strategy', models.TextField(blank=True)),
                ('priority_actions', models.JSONField(blank=True, default=list)),
                ('template_name', models.CharField(blank=True, max_length=120)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='development_plan_v2', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'individual_development_plans',
            },
        ),
        migrations.CreateModel(
            name='PositionCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=60)),
                ('dominant_foot', models.CharField(blank=True, choices=[('right', 'Direito'), ('left', 'Esquerdo'), ('both', 'Ambos')], max_length=10)),
                ('squad_role', models.CharField(blank=True, choices=[('starter', 'Titular'), ('backup', 'Reserva'), ('rotation', 'Rotacao'), ('prospect', 'Promessa')], max_length=20)),
                ('starts', models.PositiveSmallIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('hierarchy_order', models.PositiveSmallIntegerField(default=1)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('fit_to_game_model', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], max_length=10)),
                ('coach_trust_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=10)),
                ('leadership_level', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'position_competitors',
                'ordering': ['hierarchy_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TacticalGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_system', models.CharField(blank=True, max_length=30)),
                ('in_possession_system', models.CharField(blank=True, max_length=30)),
                ('out_of_possession_system', models.CharField(blank=True, max_length=30)),
                ('playing_style', models.CharField(blank=True, choices=[('possession', 'Posse'), ('transition', 'Transicao'), ('direct', 'Jogo direto'), ('high_press', 'Pressao alta'), ('mixed', 'Misto')], max_length=20)),
                ('offensive_principles', models.TextField(blank=True)),
                ('defensive_principles', models.TextField(blank=True)),
                ('physical_demands_by_position', models.TextField(blank=True)),
                ('tactical_demands_by_position', models.TextField(blank=True)),
                ('creative_freedom', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], max_length=10)),
                ('analyst_notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_model', to='valuation.careerintelligencecase')),
            ],
            options={
                'db_table': 'tactical_game_models',
            },
        ),
        migrations.CreateModel(
            name='CompetitorComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('technical', 'Tecnico'), ('tactical', 'Tatico'), ('physical', 'Fisico'), ('mental', 'Mental'), ('behavioral', 'Comportamental'), ('maturity', 'Maturidade competitiva'), ('game_model_fit', 'Adequacao ao modelo'), ('coach_trust', 'Confianca do treinador')], max_length=30)),
                ('rating', models.CharField(choices=[('inferior', 'Inferior'), ('similar', 'Similar'), ('superior', 'Superior')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='valuation.careerintelligencecase')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='valuation.positioncompetitor')),
            ],
            options={
                'db_table': 'competitor_comparisons',
                'ordering': ['competitor__hierarchy_order', 'criterion', 'id'],
                'unique_together': {('competitor', 'criterion')},
            },
        ),
    ]
