# Generated by Django 5.2.13 on 2026-04-12 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_division_options_and_more'),
        ('clubs', '0001_initial'),
        ('valuation', '0009_careerintelligencecase_careerprognosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_players', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='division_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_players', to='catalog.division'),
        ),
    ]
