# Generated by Django 5.2.13 on 2026-04-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0010_player_club_reference_player_division_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBXValueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'IA')], default='manual', max_length=10)),
                ('mention_volume', models.PositiveIntegerField(default=0)),
                ('mention_momentum', models.FloatField(default=0)),
                ('sentiment_score', models.FloatField(default=0)),
                ('estimated_reach', models.FloatField(default=0)),
                ('source_relevance', models.FloatField(default=0)),
                ('performance_rating', models.FloatField(default=0)),
                ('attention_spike', models.FloatField(default=0)),
                ('market_response', models.FloatField(default=0)),
                ('visibility_efficiency', models.FloatField(default=0)),
                ('market_perception_index', models.FloatField(default=0)),
                ('performance_impact_score', models.FloatField(default=0)),
                ('impact_correlation_score', models.FloatField(default=0)),
                ('trend_label', models.CharField(blank=True, max_length=40)),
                ('narrative_label', models.CharField(blank=True, max_length=40)),
                ('market_label', models.CharField(blank=True, max_length=80)),
                ('narrative_summary', models.TextField(blank=True)),
                ('narrative_keywords', models.JSONField(blank=True, default=list)),
                ('strategic_insights', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hbx_value_profile', to='valuation.player')),
            ],
            options={
                'db_table': 'hbx_value_profiles',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
