# Generated by Django 5.2.13 on 2026-04-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0011_hbxvalueprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbxvalueprofile',
            name='delivery_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hbxvalueprofile',
            name='source_collection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hbxvalueprofile',
            name='source_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
