# Generated by Django 5.2.13 on 2026-04-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0012_hbxvalueprofile_delivery_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmetrics',
            name='google_news_query',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='x_handle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='youtube_query',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='player',
            name='athlete_objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(blank=True, choices=[('professional', 'Profissional'), ('academy', 'Base')], max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_months_remaining',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dominant_foot',
            field=models.CharField(blank=True, choices=[('right', 'Direito'), ('left', 'Esquerdo'), ('both', 'Ambos')], max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='public_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='squad_status',
            field=models.CharField(blank=True, choices=[('starter', 'Titular'), ('backup', 'Reserva'), ('rotation', 'Rotacao'), ('limited', 'Pouco utilizado'), ('recovering', 'Retorno de lesao')], max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
