# Generated by Django 5.2.13 on 2026-04-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0013_marketingmetrics_google_news_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmetrics',
            name='collection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='instagram_engagement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='instagram_followers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='instagram_posts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='tiktok_engagement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='tiktok_followers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='tiktok_posts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='x_engagement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='x_followers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='youtube_avg_views',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='youtube_subscribers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketingmetrics',
            name='youtube_videos',
            field=models.FloatField(default=0),
        ),
    ]
