# Generated by Django 5.2.13 on 2026-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0014_marketingmetrics_collection_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='training_environment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='trajectory_score',
            field=models.FloatField(default=0),
        ),
    ]
