# Generated by Django 5.2.13 on 2026-04-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0018_athleteidentity_datasourcelog_athletesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteCareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=160)),
                ('country_name', models.CharField(blank=True, max_length=120)),
                ('division_name', models.CharField(blank=True, max_length=120)),
                ('season_label', models.CharField(blank=True, max_length=60)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('move_type', models.CharField(choices=[('permanent', 'Contrato definitivo'), ('loan', 'Emprestimo'), ('academy', 'Base'), ('promotion', 'Promocao interna'), ('trial', 'Periodo de avaliacao'), ('other', 'Outro')], default='permanent', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to='valuation.player')),
            ],
            options={
                'db_table': 'athlete_career_entries',
                'ordering': ['-is_current', '-start_date', '-id'],
            },
        ),
    ]
