# Generated by Django 5.2.13 on 2026-04-16 03:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0019_athletecareerentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('release_clause', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('renewal', 'Em renovacao'), ('expiring', 'Proximo do fim'), ('loan', 'Emprestimo'), ('free', 'Livre')], default='active', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='valuation.player')),
            ],
            options={
                'db_table': 'athlete_contracts',
                'ordering': ['-is_current', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AthleteTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_club', models.CharField(blank=True, max_length=160)),
                ('to_club', models.CharField(max_length=160)),
                ('transfer_date', models.DateField()),
                ('transfer_type', models.CharField(choices=[('permanent', 'Definitiva'), ('loan', 'Emprestimo'), ('return_loan', 'Retorno de emprestimo'), ('free', 'Livre'), ('internal', 'Promocao interna'), ('other', 'Outra')], default='permanent', max_length=20)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='valuation.player')),
            ],
            options={
                'db_table': 'athlete_transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
    ]
