# Generated by Django 5.2.13 on 2026-04-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0020_athletecontract_athletetransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoCarrieraCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('sleep_quality', models.PositiveSmallIntegerField(default=0)),
                ('hydration', models.PositiveSmallIntegerField(default=0)),
                ('nutrition', models.PositiveSmallIntegerField(default=0)),
                ('energy', models.PositiveSmallIntegerField(default=0)),
                ('focus', models.PositiveSmallIntegerField(default=0)),
                ('mood', models.PositiveSmallIntegerField(default=0)),
                ('motivation', models.PositiveSmallIntegerField(default=0)),
                ('post_error_response', models.PositiveSmallIntegerField(default=0)),
                ('soreness', models.PositiveSmallIntegerField(default=0)),
                ('recovery', models.PositiveSmallIntegerField(default=0)),
                ('treatment_adherence', models.PositiveSmallIntegerField(default=0)),
                ('injury_status', models.CharField(choices=[('none', 'Sem lesao'), ('managed', 'Controle de carga'), ('recovery', 'Em recuperacao')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_carriera_checkins', to='valuation.player')),
            ],
            options={
                'db_table': 'go_carriera_checkins',
                'ordering': ['-checkin_date', '-id'],
                'unique_together': {('player', 'checkin_date')},
            },
        ),
    ]
