# Generated by Django 5.2.13 on 2026-04-19 18:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0022_athletesnapshot_behavioral_summary_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('market_score', models.FloatField(blank=True, null=True)),
                ('marketing_score', models.FloatField(blank=True, null=True)),
                ('behavior_score', models.FloatField(blank=True, null=True)),
                ('valuation_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='scenario_lab_entries', to='valuation.player')),
            ],
            options={
                'db_table': 'scenario_lab',
                'ordering': ['-snapshot_date', '-id'],
            },
        ),
    ]
