# Generated by Django 5.2.13 on 2026-04-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('official_name', models.CharField(max_length=180, verbose_name='nome oficial')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='nome curto')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='estado')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano de fundação')),
                ('badge_url', models.URLField(blank=True, verbose_name='URL do escudo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='catalog.country', verbose_name='país')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='catalog.division', verbose_name='divisão')),
            ],
            options={
                'verbose_name': 'clube',
                'verbose_name_plural': 'clubes',
                'ordering': ['country__name', 'division__level', 'official_name'],
                'constraints': [models.UniqueConstraint(fields=('division', 'official_name'), name='unique_club_name_per_division')],
            },
        ),
    ]
