# Generated by Django 5.2.13 on 2026-04-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='código')),
                ('alternative_names', models.CharField(blank=True, help_text='Separe nomes alternativos por vírgula.', max_length=255, verbose_name='nomes alternativos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='nome curto')),
                ('level', models.PositiveSmallIntegerField(verbose_name='nível')),
                ('alternative_names', models.CharField(blank=True, help_text='Separe nomes alternativos por vírgula.', max_length=255, verbose_name='nomes alternativos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='catalog.country', verbose_name='país')),
            ],
            options={
                'verbose_name': 'divisão',
                'verbose_name_plural': 'divisões',
                'ordering': ['country__name', 'level', 'name'],
                'constraints': [models.UniqueConstraint(fields=('country', 'name'), name='unique_division_name_per_country'), models.UniqueConstraint(fields=('country', 'level'), name='unique_division_level_per_country')],
            },
        ),
    ]
