# Generated by Django 5.2.13 on 2026-04-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_brazil_divisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['country__name', 'scope', 'state', 'level', 'name'], 'verbose_name': 'divisão', 'verbose_name_plural': 'divisões'},
        ),
        migrations.RemoveConstraint(
            model_name='division',
            name='unique_division_name_per_country',
        ),
        migrations.RemoveConstraint(
            model_name='division',
            name='unique_division_level_per_country',
        ),
        migrations.AddField(
            model_name='division',
            name='scope',
            field=models.CharField(choices=[('national', 'Nacional'), ('state', 'Estadual'), ('other', 'Outra')], default='national', max_length=12, verbose_name='escopo'),
        ),
        migrations.AddField(
            model_name='division',
            name='state',
            field=models.CharField(blank=True, max_length=120, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='division',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nível'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('country', 'scope', 'state', 'name'), name='unique_division_name_per_country_scope_state'),
        ),
    ]
