# Generated by Django 5.2.13 on 2026-04-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('sport_name', models.CharField(blank=True, max_length=120, verbose_name='nome esportivo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('primary_position', models.CharField(max_length=80, verbose_name='posição principal')),
                ('secondary_positions', models.CharField(blank=True, help_text='Separe por vírgula.', max_length=180, verbose_name='posições secundárias')),
                ('dominant_foot', models.CharField(blank=True, choices=[('right', 'Direita'), ('left', 'Esquerda'), ('both', 'Ambas')], max_length=10, verbose_name='perna dominante')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='altura (cm)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='peso (kg)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('retired', 'Aposentado')], default='active', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_athletes', to='clubs.club', verbose_name='clube atual')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='catalog.country', verbose_name='nacionalidade')),
            ],
            options={
                'verbose_name': 'atleta',
                'verbose_name_plural': 'atletas',
                'ordering': ['sport_name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='camisa')),
                ('is_current', models.BooleanField(default=False, verbose_name='vínculo atual')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_history', to='athletes.athlete', verbose_name='atleta')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_history', to='clubs.club', verbose_name='clube')),
            ],
            options={
                'verbose_name': 'histórico do atleta',
                'verbose_name_plural': 'históricos dos atletas',
                'ordering': ['-is_current', '-start_date'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'club', 'start_date'), name='unique_athlete_club_period')],
            },
        ),
    ]
